# Generated by Django 6.0.4 on 2026-04-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('is_happy', models.BooleanField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
