# Generated by Django 6.0.4 on 2026-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='full_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
