# Generated by Django 6.0.4 on 2026-04-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_test_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
